# Generated by Django 4.1.4 on 2022-12-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images', verbose_name='Imagen'),
        ),
    ]
