# Generated by Django 4.1.4 on 2022-12-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_step_alter_history_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado el'),
        ),
        migrations.AlterField(
            model_name='history',
            name='star_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
    ]
